server:
  port: 8080

spring:
  application:
    name: request-server

url:
  server:
    response:
      endpoint: http://localhost:8081/response/rest-template
      retry: /retry


restTemplate:
  connectTimeOut: 5
  readTimeOut: 5

logging:
  level:
    web: debug