server:
  port: 8080

spring:
  application:
    name: request-server

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: BASIC
          openFeignClient:
            connect-timeout: 1000
            read-timeout: 1000
            logger-level: FULL
            request-interceptors:
              - io.dongvelop.requestserver.common.AuthorizationRequestInterceptor

      retry:
        openFeignClient:
          period: 100
          duration: 3
          maxAttempt: 3


url:
  server:
    response:
      endpoint: http://localhost:8081/response
      retry: /retry
      timeout: /timeout


restTemplate:
  connectTimeOut: 5
  readTimeOut: 5

webClient:
  maxMemorySize: 2097152 # 2 * 1024 * 1024
  timeout:
    connect: 5000
    response: 5
    read: 5
    write: 5
  retry:
    maxAttempt: 3
    delay: 1

logging:
  level:
    web: debug
    reactor: debug
    feign: debug
    io.dongvelop.requestserver.service: debug