#### HttpInterface 정상 케이스 예시 ####
POST localhost:8080/request/http-interface
Content-Type: application/json

{
  "writer": "Lee Dongyeop",
  "message": "HttpInterface Example"
}

##########################################

#### HttpInterface Retry 케이스 예시 ####
POST localhost:8080/request/http-interface/retry
Content-Type: application/json

{
  "writer": "Lee Dongyeop",
  "message": "HttpInterface Retry Example"
}

##########################################

#### HttpInterface : 에러 코드별로 분리 처리 예시 ####
POST localhost:8080/request/http-interface/error
Content-Type: application/json

{
  "writer": "Lee Dongyeop",
  "message": "HttpInterface Error Handling Example"
}

##########################################